### ISSUE TITLE
Which version to use to reproduce Table 3?

### ISSUE THREAD

**Issue by daahuang** [mayubo2333/MMLongBench-Doc#2]
Seems that `data/samples.json` is updated (1082 questions) and is different from the dataset on HuggingFace (1091 questions).
Which version should I use to reproduce Table 3 in the paper?

**Comment by mayubo2333** [comment]
The results in Table 3 are from datasets on Huggingface (1091 questions).

However, the datasets on Github (1082 questions) are newer version, in which we further remove 9 unqualified questions. These two version datasets have very very similar performance on GPT-4o (with about 0.5% difference). Based on the newer version (1082 questions), we will release updated paper and a leaderboard , maybe shortly after the ICLR deadline.

**Comment by daahuang** [comment]
Got it, thanks!
